### PR TITLE
Remove Unix depencency for Time_ns debugging output (closes #42)

### LINKED ISSUE #42: Some Unix references
`Unix` is referenced from `core_kernel.cmxa` - probably due to the `Unix` references in `src/time_ns.ml`?

### PR DESCRIPTION
**Pull request by raboof**
A comment states that:

  Note that the [sexp] below is implemented only for some debug text later in
  this module. It is not exposed in the mli

To be quite honest I haven't been able to trigger this code normally at
all - in any case I've removed the Unix dependency when generating a
human-readable representation.

### CODE REVIEW

**Comment by diml** [comment]
The use of `Unix` in `Time_ns` should be gone in the next release as discussed in #21

**Comment by raboof** [comment]
Ah - so do I understand correctly that Jane Street has already privately made that change and it will be pushed out to github as soon as the next version is released? 

When can I expect the next release?

**Comment by diml** [comment]
@raboof yes. The next release should come very soon

**Comment by raboof** [comment]
OK thanks! Looking forward to it!

**Pull request closed without merging**
